{{- if ne .Values.strategy.type "rolling" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "saas-web-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saas-web-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "saas-web-application.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.strategy.type "blue-green" }}
    blueGreen:
      activeService: {{ .Values.blueGreen.activeService }}
      previewService: {{ .Values.blueGreen.previewService }}
      autoPromotionEnabled: {{ .Values.blueGreen.autoPromotionEnabled }}
      {{- with .Values.blueGreen.autoPromotionSeconds }}
      autoPromotionSeconds: {{ . }}
      {{- end }}
      {{- with .Values.blueGreen.scaleDownDelaySeconds }}
      scaleDownDelaySeconds: {{ . }}
      {{- end }}
      {{- with .Values.blueGreen.previewReplicaCount }}
      previewReplicaCount: {{ . }}
      {{- end }}
    {{- else if eq .Values.strategy.type "canary" }}
    canary:
      {{- with .Values.canary.canaryService }}
      canaryService: {{ . }}
      {{- end }}
      {{- with .Values.canary.stableService }}
      stableService: {{ . }}
      {{- end }}
      {{- if .Values.canary.trafficRouting }}
      trafficRouting:
        {{- toYaml .Values.canary.trafficRouting | nindent 8 }}
      {{- end }}
      {{- with .Values.canary.steps }}
      steps:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "saas-web-application.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- include "saas-web-application.podSpec" . | nindent 6 }}
{{- end }}
