{{- if .Values.secrets.sealed.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "saas-web-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData: {}
  template:
    metadata:
      name: {{ include "saas-web-application.fullname" . }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
    stringData:
      JWT_SECRET: ""
{{- end }}
